var dataContent = [{
  "type": "section",
  "class": "timeline-section-left",
  "id": "",
  "name": "",
  "Sammlungsbereich": "",
  "Gattung": "",
  "year": "-3760",
  "year1": "",
  "metadata": "",
  "text": "Das Jahr 1 der jüdischen Zeitrechnung. ",
  "emNumber": "",
  "em": "",
  "subtitle": "",
  "Link": "",
  "imgName": "",
  "imgLink": ""
}, {
  "type": "section",
  "class": "timeline-section-right",
  "id": "",
  "name": "",
  "Sammlungsbereich": "",
  "Gattung": "",
  "year": "-1140",
  "year1": "",
  "metadata": "",
  "text": "Moses führt die Israeliten aus der 400 Jahre andauernden Knechtschaft in Ägypten. ",
  "emNumber": "",
  "em": "",
  "subtitle": "",
  "Link": "",
  "imgName": "",
  "imgLink": ""
}, {
  "type": "section",
  "class": "timeline-section-left",
  "id": "",
  "name": "",
  "Sammlungsbereich": "",
  "Gattung": "",
  "year": "-1050",
  "year1": "",
  "metadata": "",
  "text": "Saul wird der erste König der Normadenstämme in Israels. Hauptstadt des Reiches wird Jerusalem.",
  "emNumber": "",
  "em": "",
  "subtitle": "",
  "Link": "",
  "imgName": "",
  "imgLink": ""
}, {
  "type": "section",
  "class": "timeline-section-left",
  "id": "",
  "name": "",
  "Sammlungsbereich": "",
  "Gattung": "",
  "year": "-925",
  "year1": "",
  "metadata": "",
  "text": "Nach dem Tod von König Salamon verfällt das Reich in das Südreich »Juda« und das Nordreich »Israel«.",
  "emNumber": "",
  "em": "",
  "subtitle": "",
  "Link": "",
  "imgName": "",
  "imgLink": ""
}, {
  "type": "section",
  "class": "timeline-section-right",
  "id": "",
  "name": "",
  "Sammlungsbereich": "",
  "Gattung": "",
  "year": "-587",
  "year1": "",
  "metadata": "",
  "text": "Eroberung Jerusalems und Zerstörung des Tempels durch die Babylonier. Verschleppung der jüdaischen Oberschicht nach&nbsp;Babylon.\n",
  "emNumber": "",
  "em": "",
  "subtitle": "",
  "Link": "",
  "imgName": "",
  "imgLink": ""
}, {
  "type": "section",
  "class": "timeline-section-left",
  "id": "",
  "name": "",
  "Sammlungsbereich": "",
  "Gattung": "",
  "year": "-539",
  "year1": "",
  "metadata": "",
  "text": "Der persische König Cyrus erobert Babylon und erlaubt den Judäern in ihre Heimat zurückzukehren.",
  "emNumber": "",
  "em": "",
  "subtitle": "",
  "Link": "",
  "imgName": "",
  "imgLink": ""
}, {
  "type": "section",
  "class": "timeline-section-right",
  "id": "",
  "name": "",
  "Sammlungsbereich": "",
  "Gattung": "",
  "year": "-538",
  "year1": "",
  "metadata": "",
  "text": "Nach Jahrzehnten in babylonischer Gefangenschaft kommen die letzten Heimkehrer nach Jerusalem zurück und bezeichnen sich selbst erstmals als&nbsp;Juden.",
  "emNumber": "",
  "em": "",
  "subtitle": "",
  "Link": "",
  "imgName": "",
  "imgLink": ""
}, {
  "type": "section",
  "class": "timeline-section-left",
  "id": "",
  "name": "",
  "Sammlungsbereich": "",
  "Gattung": "",
  "year": "-333",
  "year1": "",
  "metadata": "",
  "text": "Alexander der Große erobert den gesamten Vorderen Orient. Sein hellenistischer Einfluss führt zu einem Verbot der alten jüdischen Traditionen. ",
  "emNumber": "",
  "em": "",
  "subtitle": "",
  "Link": "",
  "imgName": "",
  "imgLink": ""
}, {
  "type": "section",
  "class": "timeline-section-right",
  "id": "",
  "name": "",
  "Sammlungsbereich": "",
  "Gattung": "",
  "year": "-164",
  "year1": "",
  "metadata": "",
  "text": "Judas, dem Führer der Rebellen gelingt den kriegerische Durchbruch. Er zieht mit seine Gefolgsleuten in Jerusalem ein und erobert den Tempel zurück.",
  "emNumber": "",
  "em": "",
  "subtitle": "",
  "Link": "",
  "imgName": "",
  "imgLink": ""
}, {
  "type": "section",
  "class": "timeline-section-left",
  "id": "",
  "name": "",
  "Sammlungsbereich": "",
  "Gattung": "",
  "year": "-63",
  "year1": "",
  "metadata": "",
  "text": "Mit der Eroberung Jerusalems durch den römischen Feldherrn Pompejus entsteht eine Abhängigkeit der jüdischen Herrscher von Rom.",
  "emNumber": "",
  "em": "",
  "subtitle": "",
  "Link": "",
  "imgName": "",
  "imgLink": ""
}, {
  "type": "section",
  "class": "timeline-section-right",
  "id": "",
  "name": "",
  "Sammlungsbereich": "",
  "Gattung": "",
  "year": "321",
  "year1": "",
  "metadata": "",
  "text": "Erste jüdische Gemeinden in Köln.",
  "emNumber": "",
  "em": "",
  "subtitle": "",
  "Link": "",
  "imgName": "",
  "imgLink": ""
}, {
  "type": "section",
  "class": "timeline-section-left",
  "id": "",
  "name": "",
  "Sammlungsbereich": "",
  "Gattung": "",
  "year": "1147",
  "year1": "",
  "metadata": "",
  "text": "Erneute Verfolgung während des 2. Kreuzzuges.",
  "emNumber": "",
  "em": "",
  "subtitle": "",
  "Link": "",
  "imgName": "",
  "imgLink": ""
}, {
  "type": "section",
  "class": "timeline-section-right",
  "id": "",
  "name": "",
  "Sammlungsbereich": "",
  "Gattung": "",
  "year": "1348",
  "year1": "",
  "metadata": "",
  "text": "Während der Pest erfolgt die weitgehende Ermordung der jüdischen Bevölkerung in Mitteleuropa.",
  "emNumber": "",
  "em": "",
  "subtitle": "",
  "Link": "",
  "imgName": "",
  "imgLink": ""
}, {
  "type": "content",
  "class": "content-block-left",
  "id": "yearDivision",
  "name": "Der Heilige Werner von Oberwesel \n",
  "Sammlungsbereich": "Kunst",
  "Gattung": "Gemälde\nAnonym",
  "year": "",
  "year1": "1711",
  "metadata": "Öl auf Leinwand</br>1711</br>\n113 &#215; 71,5 cm\n",
  "text": "Inschrift: Wernerus ein junger Bauernsohn zu Wesel (1271-1284) ist von Juden gefangen, hart gepeiniget, und am Charfreytag Christo zu spoth gekreuzigt worden\" <sup>01</sup>",
  "emNumber": "(01)",
  "em": "Viele Christen glaubten, Juden würden für ihre religiösen Rituale Menschenblut benutzen.",
  "subtitle": "Literatur- und Abbildungsnachweis: Stiftung Jüdisches Museum Berlin (Hg.): Geschichten einer Ausstellung. Zwei Jahrtausende deutsch-jüdische Geschichte, Kat. Jüdisches Museum Berlin, Berlin: Proprietas-Verlag, 2. Auflage, 2002",
  "Link": "http://objekte.jmberlin.de/object/jmb-obj-107679",
  "imgName": "132846_image.jpg",
  "imgLink": "http://objekte.jmberlin.de/image/jmb-img-132846"
}, {
  "type": "section",
  "class": "timeline-section-right",
  "id": "",
  "name": "",
  "Sammlungsbereich": "",
  "Gattung": "",
  "year": "1714",
  "year1": "",
  "metadata": "",
  "text": "Einweihung der ersten öffentlichen Synagoge Berlins.",
  "emNumber": "",
  "em": "",
  "subtitle": "",
  "Link": "",
  "imgName": "",
  "imgLink": ""
}, {
  "type": "section",
  "class": "timeline-section-right",
  "id": "",
  "name": "",
  "Sammlungsbereich": "",
  "Gattung": "",
  "year": "1750",
  "year1": "",
  "metadata": "",
  "text": "Berlin wird das geistige und kulturelle Zentrum des deutschen Judentums. Wichtigster Vertreter der jüdischen »Emanzipation« ist Moses Mendelssohn. ",
  "emNumber": "",
  "em": "",
  "subtitle": "",
  "Link": "",
  "imgName": "",
  "imgLink": ""
}, {
  "type": "content",
  "class": "content-block-right",
  "id": "",
  "name": "Schutzkonzession zum Handel mit Wolle",
  "Sammlungsbereich": "Archiv",
  "Gattung": "Urkunde",
  "year": "",
  "year1": "1775",
  "metadata": "Tinte auf Papier</br>Berlin, 01.06.1775</br>\n33 &#215; 20,5 cm",
  "text": "Zwei Seiten. Concession des Königs Friedrich II. für Peretz Marcus zu Driesen betr. Erlaubnis zum Ankauf von Wolle.\nJuden mussten besondere Handelskonzessionen erwerben.",
  "emNumber": "",
  "em": "",
  "subtitle": "",
  "Link": "http://objekte.jmberlin.de/object/jmb-obj-103242",
  "imgName": "606715_image.jpg",
  "imgLink": "http://objekte.jmberlin.de/image/jmb-img-606715"
}, {
  "type": "section",
  "class": "timeline-section-left",
  "id": "",
  "name": "",
  "Sammlungsbereich": "",
  "Gattung": "",
  "year": "1778",
  "year1": "",
  "metadata": "",
  "text": "Gründung der »Jüdischen Freischule«, die die Ideen der Aufklärung unter der jüdischen Bevölkerung verbreiten soll.",
  "emNumber": "",
  "em": "",
  "subtitle": "",
  "Link": "",
  "imgName": "",
  "imgLink": ""
}, {
  "type": "content",
  "class": "content-block-middle-left",
  "id": "",
  "name": "Juden-Kalender auf das Schald Jahr 1780",
  "Sammlungsbereich": "Archiv",
  "Gattung": "Buch\nMarcus Gerson (gest. 30.3.1792)",
  "year": "",
  "year1": "1780",
  "metadata": "Buchdruck</br>Berlin,1780</br>\n14 &#215; 8,5 cm",
  "text": "Gedruckt von Marcus Gerson unter Approbation der von seiner königlichen Majestät in Preussen in der Residenz Berlin gestifteten Academie der Wissenschaften.\nHebräischer Text und Holzschnitte zu den 12 Sternzeichen, die den hebräischen Monatsbezeichnungen zugeordnet sind.\nDiese Kalender waren ein unverzichtbares Hilfsmittel für jüdische Händler und Händlerinnen. Mit ihnen konnten sie ihre Geschäftsreisen und die Einhaltung der Feiertage planen - und damit Beruf und Religion miteinander vereinbaren.",
  "emNumber": "",
  "em": "",
  "subtitle": "",
  "Link": "http://objekte.jmberlin.de/object/jmb-obj-560452",
  "imgName": "560539_image.jpg",
  "imgLink": "http://objekte.jmberlin.de/image/jmb-img-560539"
}, {
  "type": "section",
  "class": "timeline-section-left",
  "id": "",
  "name": "",
  "Sammlungsbereich": "",
  "Gattung": "",
  "year": "1842",
  "year1": "",
  "metadata": "",
  "text": "",
  "emNumber": "",
  "em": "",
  "subtitle": "",
  "Link": "",
  "imgName": "",
  "imgLink": ""
}, {
  "type": "content",
  "class": "content-block-middle-right",
  "id": "",
  "name": "Naturalisationspatent, ausgestellt für Schie Adam",
  "Sammlungsbereich": "Archiv",
  "Gattung": "Urkunde",
  "year": "",
  "year1": "1842",
  "metadata": "Papier, Tinte</br>\nPosen, 27.&#x2009;08.1842</br>\n34 &#215; 21,4 cm\n",
  "text": "Doppelblatt, Vordruck handschriftlich ausgefüllt, Gebührenstempel für Schie Adam (geb. 1800).\nIn der preußischen Provinz Posen teilte ein klassisches Erziehungsgesetz seit 1833 die Juden in zwei Klassen: Wer bestimmte Voraussetzungen erfüllte, wie Grundstücksbesitz, ein angesehenes Gewerbe, Vermögen, die Beherrschung der deutschen Sprache, erhielt ein Naturalisationspatent, das eine weitgehende Gleichstellung bedeutete. Der größte Teil der jüdischen Bevölkerung gehörte jedoch zu den \"Gedulteten\" mit erheblich eingeschränkten Rechten.<sup>02</sup>",
  "emNumber": "(02)",
  "em": "Die \"Gedulteten\" waren rechtlos, die Heirat war ihnen verboten, wenn sie nicht einen Juden aus einer oberen Klasse heirateten.",
  "subtitle": "",
  "Link": "http://objekte.jmberlin.de/object/jmb-obj-169504",
  "imgName": "169573_image.jpg",
  "imgLink": "http://objekte.jmberlin.de/image/jmb-img-169573"
}, {
  "type": "content",
  "class": "content-block-left",
  "id": "",
  "name": "Verzeichnis vorgenommener Beschneidungen",
  "Sammlungsbereich": "Archiv",
  "Gattung": "Manuskript, Typoskript",
  "year": "",
  "year1": "1858",
  "metadata": "Leder, Papier, Tinte</br>\nSchweitz, 1858 – 1905</br>\n19 &#215; 11 cm",
  "text": "Mohelbuch mit Eintrag der Beschneidungen, die vom Mohel Herrman Hirschberg durchgeführt wurden. Er nahm zwischen 1858 und 1905 an die 693 Beschneidungen vor. Die Daten - Name des beschnittenen Kindes und seines Vaters, Ort und Tag der Geburt, Ort und Tag der Beschneidung sind links in Deutsch, rechts in Hebräisch mit Tinte notiert.",
  "emNumber": "",
  "em": "",
  "subtitle": "",
  "Link": "http://objekte.jmberlin.de/object/jmb-obj-103452",
  "imgName": "121444_image.jpg",
  "imgLink": "http://objekte.jmberlin.de/image/jmb-img-121444"
}, {
  "type": "section",
  "class": "timeline-section-right",
  "id": "",
  "name": "",
  "Sammlungsbereich": "",
  "Gattung": "",
  "year": "1881",
  "year1": "",
  "metadata": "",
  "text": "Verfolgungen und Pogrome vertreiben 2 Millionen Juden in&nbsp;Russland. ",
  "emNumber": "",
  "em": "",
  "subtitle": "",
  "Link": "",
  "imgName": "",
  "imgLink": ""
}, {
  "type": "content",
  "class": "content-block-right",
  "id": "",
  "name": "Miniaturporträt Livia Cohen in zugehöriger Schatulle",
  "Sammlungsbereich": "Kunst",
  "Gattung": "Memorabilia (dreidimensional)\nErnst Bastanier (geb. 27.1.1842)",
  "year": "",
  "year1": "1886",
  "metadata": "Porzellan, Messing, Samt, Seide, Leder</br>\nBerlin, 1886</br>\nBildnis: 4,5 &#215; 3,3 cm\n",
  "text": "Farbiges Miniaturporträt eines Mädchens in Schatulle mit herausnehmbarem Rahmen.\nRotbraune Lederkassette, mit blauer Seide gefüttert. Das Paar heiratete 1898, es blieb kinderlos. Die Verfolgungszeit während des Nationalsozialismus überlebte Livia (1872-1957) Kratz mit Hilfe ihres Mannes in Berlin in einer \"Mischehe\", nach dem Krieg wurde sie als \"Opfer des Faschismus\" anerkannt. <sup>03</sup>",
  "emNumber": "(03)",
  "em": "Nach dem Krieg wurde Juden als Opfer des Faschismus anerkannt.",
  "subtitle": "",
  "Link": "http://objekte.jmberlin.de/object/jmb-obj-102389",
  "imgName": "121175_image.jpg",
  "imgLink": "http://objekte.jmberlin.de/image/jmb-img-121175"
}, {
  "type": "content",
  "class": "content-block-middle-left",
  "id": "",
  "name": "Das Ehepaar Gertrud und Max Michalski mit ihrem ersten Kind",
  "Sammlungsbereich": "Fotografische Sammlung",
  "Gattung": "Fotografie (s/w)",
  "year": "",
  "year1": "1907",
  "metadata": "Fotografie, auf Karton aufgezogen</br>\nBerlin, um 1907</br>\n16,7 &#215; 10,7 cm\n",
  "text": "Atelieraufnahme; Mann und Frau, sie mit Baby auf dem Arm. Er im dunklen Anzug mit Krawatte und Ring am Ringfinger seiner rechten Hand. Sie im aufwendigen Kleid mit Besätzen und Spitzenkragen, Halskette und Armband; das Baby im weißen Spitzenkleidchen.",
  "emNumber": "",
  "em": "",
  "subtitle": "",
  "Link": "http://objekte.jmberlin.de/object/jmb-obj-107440",
  "imgName": "117791_image.jpg",
  "imgLink": "http://objekte.jmberlin.de/image/jmb-img-117791"
}, {
  "type": "content",
  "class": "content-block-middle-right",
  "id": "",
  "name": "Bestätigung für die Schmuckabgabe bei der Reichsbank",
  "Sammlungsbereich": "Archiv",
  "Gattung": "Druckerzeugnis",
  "year": "",
  "year1": "1916",
  "metadata": "Papier, Tinte</br>\nBerlin, 08.12.1916</br>\n16 &#215; 24 cm\n",
  "text": "Bestätigung an Henriette Hartog (1891-1979) für Schmuckabgabe bei der Reichsbank, Vordruck, handschriftlich ausgefüllt, Berlin, 08.12.1916.</br>\nHandschriftlich eingesetzt wurden der Name \"Frau Dr. Carl Hartog\", die Summe \"61,50\", das Datum \"Berlin, 8. Dezember\" sowie die Unterschriften des Ehrenausschusses der Geldankaufstelle. <sup>04</sup>",
  "emNumber": "(04)",
  "em": "Man müsse ihnen \"all das wegnehmen, was die Auswanderung hindert\", schlug Hermann Göring vor.",
  "subtitle": "",
  "Link": "http://objekte.jmberlin.de/object/jmb-obj-404423?cid=189419",
  "imgName": "536349_image.jpg",
  "imgLink": "http://objekte.jmberlin.de/image/jmb-img-536349"
}, {
  "type": "content",
  "class": "content-block-left",
  "id": "",
  "name": "Militärische Skizze zu einer Gefechtssituation im Schützengraben",
  "Sammlungsbereich": "Kunst",
  "Gattung": "Handzeichnung, Aquarell\nErnst Marcus (5.9.1893 - 25.7.1917)",
  "year": "",
  "year1": "1916",
  "metadata": "Bleistift auf Papier</br>\nWolhynien, 1916 – 1917</br>\n9,2 &#215; 14,4 cm",
  "text": "Planzeichnung eines Schützengrabens. Eingezeichnet sind zwei Unterstände, einer davon bezeichnet als \"mein Unterstand\", ein Teil des Grabens sowie der Weg zur Latrine. Neben dem Unterstand von Ernst Marcus ist ein Granattrichter verzeichnet, darum herum Sprengstücke; die Latrine ist bezeichnet mit \"wo ich war\" - offenbar diente die Skizze zur Erläuterung einer in einem Brief beschriebenen Gefechtssituation, in der Marcus durch Zufall knapp dem Tod entging.",
  "emNumber": "",
  "em": "",
  "subtitle": "",
  "Link": "http://objekte.jmberlin.de/object/jmb-obj-259289",
  "imgName": "263420_image.jpg",
  "imgLink": "http://objekte.jmberlin.de/image/jmb-img-263420"
}, {
  "type": "section",
  "class": "timeline-section-right",
  "id": "",
  "name": "",
  "Sammlungsbereich": "",
  "Gattung": "",
  "year": "1917",
  "year1": "",
  "metadata": "",
  "text": "Der britische Außenminister Arthur James ermöglicht dem jüdischen Volk mit der »Balfour-Deklaration« die Staatsgründung in Palästina.",
  "emNumber": "",
  "em": "",
  "subtitle": "",
  "Link": "",
  "imgName": "",
  "imgLink": ""
}, {
  "type": "content",
  "class": "content-block-right",
  "id": "",
  "name": "Spendenbüchse des jüdischen Nationalfonds",
  "Sammlungsbereich": "Judaica/Angewandte Kunst",
  "Gattung": "dreidim. Gegenstand des weltlichen Gebrauchs",
  "year": "",
  "year1": "1920",
  "metadata": "Palästina oder Deutschland</br>\num 1920</br>\n12,8 &#215; 9,8 &#215; 5 cm\n",
  "text": "Auf dem 5. Zionistenkongress, der 1901 stattfand, wurde ein nationaler jüdischer Fund gegründet. Mit diesen Geldern sollte Land in Eretz Israel erworben werden, um dem Jüdischen Volk dort eine Heimstatt zu schaffen. Im Jahre 1901 wurde eine \"Pushke\" entworfen, die länderübergreifend in Privathaushalten, in Schulen und Synagogen für Spendensammlungen verwendet wurde. Die Gestaltung der Spendenbüchse wechselte im Laufe der Jahre, aber die \"Blue Box\", in den Zwanziger Jahren eingeführt, wurde zu einem zionistischen Symbol.",
  "emNumber": "",
  "em": "",
  "subtitle": "Literatur- und Abbildungsnachweis:\nVgl. Ontario Jewish Archives, Acc. No. 77-8/30, Artifact 12, datiert 1920.\nBeschriftung Rückseite: Klebezettelreste rückseitig Beschriftung: \"No./ [...] aláirása\" (=&nbsp;Unterschrift/Signatur) und Reste handschriftlicher Beschriftung unten: \"a persely tulajd\" (= Die Büchse gehört)",
  "Link": "http://objekte.jmberlin.de/object/jmb-obj-106101",
  "imgName": "121517_image.jpg",
  "imgLink": "http://objekte.jmberlin.de/image/jmb-img-121517"
}, {
  "type": "content",
  "class": "content-block-middle-left",
  "id": "",
  "name": "Tabakdose aus der Produktion der Haël-Werkstätten",
  "Sammlungsbereich": "Judaica/Angewandte Kunst",
  "Gattung": "dreidim. Gegenstand des weltlichen Gebrauchs\nMargarete Heymann-Loebenstein (später Marks) (1899 - 1990), Haël-Werkstätten für künstlerische Keramik",
  "year": "",
  "year1": "1923",
  "metadata": "Steingut, glasiert</br>\nMarwitz, 1923 – 1933</br>\n10 &#215; &#8709; 15,5 cm",
  "text": "Dieser Tabakdosentypus wurde in den 1920er Jahren in den \"Haël-Werkstätten für künstlerische Keramik\" hergestellt.\nNach 1933 musste Margarete Heymann-Loebenstein, die doppelt als Jüdin und moderne Künstlerin von den Nationalsozialisten diffamiert wurde, die Produktion ihres Betriebs einstellen. Im Jahr 1934 wurden die Haël-Werkstätten arisiert, zwei Jahre darauf gelang der Keramikerin die Emigration nach England.",
  "emNumber": "",
  "em": "",
  "subtitle": "Literatur- und Abbildungsnachweis:\nHaël-Werkstätten, Verkaufskatalog um 1930, Nr. 448 (Abb.). Vergleichsobjekt: Bröhan-Museum: Avantgarde für den Alltag. Jüdische Keramikerinnen in Deutschland 1919-1933, Ausst.Kat., Berlin 1912, S. 63, Abb. 37.",
  "Link": "http://objekte.jmberlin.de/object/jmb-obj-234762",
  "imgName": "234763_image.jpg",
  "imgLink": "http://objekte.jmberlin.de/image/jmb-img-234763"
}, {
  "type": "section",
  "class": "timeline-section-left",
  "id": "",
  "name": "",
  "Sammlungsbereich": "",
  "Gattung": "",
  "year": "1933",
  "year1": "",
  "metadata": "",
  "text": "Aufruf zum Judenboykott durch die Nationalsozialisten, Beginn der systematischen Judenverfolgungen.",
  "emNumber": "",
  "em": "",
  "subtitle": "",
  "Link": "",
  "imgName": "",
  "imgLink": ""
}, {
  "type": "content",
  "class": "content-block-middle-right",
  "id": "",
  "name": "Plakat der Jüdischen</br>Winterhilfe",
  "Sammlungsbereich": "Fotografische Sammlung",
  "Gattung": "Fotografie (s/w)\nHerbert Sonnenfeld (29.9.1906 - 1972)",
  "year": "",
  "year1": "1933",
  "metadata": "Fotografie (s/w-Negativfilm)</br>\nBerlin, 1933 – 1938</br>\n3,6 &#215; 2,4 cm</br>\n",
  "text": "Plakat von Herbert Sonnenfeld für die Jüdische Winterhilfe: ein umgeworfener Würfelbecher und drei Würfel, daneben die Aufschrift \"Ungleich fallen die Würfel des Lebens! Also helft!\" <sup>05</sup>",
  "emNumber": "(05)",
  "em": "Der Winter steht vor der Türe, die Not ist groß, größer als je zuvor!",
  "subtitle": "",
  "Link": "http://objekte.jmberlin.de/object/jmb-obj-166616",
  "imgName": "166617_image.jpg",
  "imgLink": "http://objekte.jmberlin.de/image/jmb-img-166617"
}, {
  "type": "content",
  "class": "content-block-left",
  "id": "",
  "name": "Plakat der Jüdischen</br>Winterhilfe",
  "Sammlungsbereich": "Fotografische Sammlung",
  "Gattung": "Fotografie (s/w)\nHerbert Sonnenfeld (29.9.1906 - 1972)",
  "year": "",
  "year1": "1933",
  "metadata": "Fotografie (s/w-Negativfilm)</br>\nBerlin, 1933 – 1938</br>\n3,6 &#215; 2,4 cm</br>\n",
  "text": "Plakat von Herbert Sonnenfeld für die Jüdische Winterhilfe: Münzen auf schwarzem Hintergrund, darüber die Aufschrift \"Jeder Groschen hilft!\"",
  "emNumber": "",
  "em": "",
  "subtitle": "",
  "Link": "http://objekte.jmberlin.de/object/jmb-obj-166620?cid=254431",
  "imgName": "166624_image.jpg",
  "imgLink": "http://objekte.jmberlin.de/image/jmb-img-166624"
}, {
  "type": "content",
  "class": "content-block-right",
  "id": "",
  "name": "Plakat der Jüdischen</br>Winterhilfe",
  "Sammlungsbereich": "Sammlungsbereich",
  "Gattung": "Fotografie (s/w)\nHerbert Sonnenfeld (29.9.1906 - 1972)",
  "year": "",
  "year1": "1933",
  "metadata": "Fotografie (s/w-Negativfilm)</br>\nBerlin, 1933 – 1938</br>\n3,6 &#215; 2,4 cm</br>",
  "text": "Plakat von Herbert Sonnenfeld für die Jüdische Winterhilfe: ein Karteikasten, darüber die Aufschrift \"Spende!- Tausende warten!\".",
  "emNumber": "",
  "em": "",
  "subtitle": "",
  "Link": "http://objekte.jmberlin.de/object/jmb-obj-166625",
  "imgName": "166626_image.jpg",
  "imgLink": "http://objekte.jmberlin.de/image/jmb-img-166626"
}, {
  "type": "content",
  "class": "content-block-middle-left",
  "id": "",
  "name": "Kündigung der Arbeitsstelle für Gertha Kroto ",
  "Sammlungsbereich": "Archiv",
  "Gattung": "Manuskript, Typoskript",
  "year": "",
  "year1": "1933",
  "metadata": "Papier, Stempelfarbe</br>\nBerlin, 28.&#x2009;04.1933</br>\n32,9 &#215; 20,8 cm\n",
  "text": "Gertha Kroto (1893-1972) wird in diesem Schreiben mitgeteilt, dass ihre Anstellung als Zahnarztassistentin in der Klinik Müllerstr. 4 zum 31. Mai 1933 vorsorglich gekündigt wird. \nIn der Folge des \"Gesetzes zur Wiederherstellung des Berufsbeamtentums\" regelte eine Verordnung vom 22. April 1933 die Zulassung von Kassenärzten und ermöglichte den Ausschluss jüdischer Ärzte. Sie verloren dadurch den größten Teil ihrer Patienten. Im Juni 1933 entzog ihr der Berliner Landesverband der Zahnärzte Deutschlands die Kassenzulassung, so dass sie ihre Praxis schließen musste. Gertha Kroto emigrierte mit ihrer Familie nach England <sup>06</sup>",
  "emNumber": "(06)",
  "em": "Es ist erlaubt jüdische und politisch missliebige Beamte aus dem Dienst zu entfernen.",
  "subtitle": "",
  "Link": "http://objekte.jmberlin.de/object/jmb-obj-221011",
  "imgName": "465588_image.jpg",
  "imgLink": "http://objekte.jmberlin.de/image/jmb-img-465588"
}, {
  "type": "content",
  "class": "content-block-middle-right",
  "id": "",
  "name": "Emigrantinnen beim Tanz auf einem Schiff nach Palästina",
  "Sammlungsbereich": "Fotografische Sammlung",
  "Gattung": "Fotografie (s/w)\nHerbert Sonnenfeld (29.9.1906 - 1972)",
  "year": "",
  "year1": "1934",
  "metadata": "Fotografie (s/w-Negativfilm)</br>\nPalästina, um 1934</br>\n2,4 &#215; 3,6 cm</br>\n",
  "text": "Junge Frauen tanzen in Paaren auf einem nicht identifizierten Auswanderungsschiff nach Palästina.",
  "emNumber": "    ",
  "em": "",
  "subtitle": "",
  "Link": "http://objekte.jmberlin.de/object/jmb-obj-146603?cid=240404",
  "imgName": "146604_image.jpg",
  "imgLink": "http://objekte.jmberlin.de/image/jmb-img-146604"
}, {
  "type": "section",
  "class": "timeline-section-left",
  "id": "",
  "name": "",
  "Sammlungsbereich": "",
  "Gattung": "",
  "year": "1935",
  "year1": "",
  "metadata": "",
  "text": "Durch die »Nürnberger Gesetze« werden Juden zu Staatsbürgern zweiter Klasse.",
  "emNumber": "",
  "em": "",
  "subtitle": "",
  "Link": "",
  "imgName": "",
  "imgLink": ""
}, {
  "type": "content",
  "class": "content-block-left",
  "id": "",
  "name": "Fahne mit Davidstern",
  "Sammlungsbereich": "Alltagskultur",
  "Gattung": "Textil (weltlicher Gebrauch)\nMartin Fried-Lander, Martin Fried-Lander",
  "year": "",
  "year1": "1935",
  "metadata": "Baumwolle, Bleiband im Saum eingenäht;</br>\nBerlin, 1935</br>\n115 &#215; 90,5 cm\n",
  "text": "Aus Protest gegen die Nürnberger \"Rassengesetze\" vom 15. September 1935 hängte Martin Friedländer zwei Wochen später, am Tag des jüdischen Neujahrsfestes, die selbstgenähte Fahne aus dem Fenster seiner Wohnung in der Berliner Linienstraße. Später nahm er sie mit nach Australien in die Emigration. <sup>07</sup>",
  "emNumber": "(07)",
  "em": "Es war die rechtliche Grundlage für die Verfolgung der Juden in Deutschland geschaffen. Antisemitismus war fortan nicht nur legal, sondern gesetzlich verordnet.",
  "subtitle": "Literatur- und Abbildungsnachweis:\nBendt, Vera: Judaica-Katalog, Kat. Berlin-Museum / Abteilung Jüdisches Museum, Berlin: Jüdisches Museum 1989, Umschlagbild und S. 108 (Abb. 47). Stiftung Jüdisches Museum Berlin (Hg.): Geschichten einer Ausstellung. Zwei Jahrtausende deutsch&#8209;jüdische Geschichte, Kat. Jüdisches Museum Berlin, Berlin: Proprietas-Verlag, 2. Auflage, 2002. Heft \"7x blau-weiß\", Artikel zur Fahne von Vera Bendt, in: Jüdisches Museum Berlin (Hg.): gesammelt gefaltet gezählt, Nicolai Verlag 2009.",
  "Link": "http://objekte.jmberlin.de/object/jmb-obj-107625",
  "imgName": "437933_image.jpg",
  "imgLink": "http://objekte.jmberlin.de/image/jmb-img-437933"
}, {
  "type": "content",
  "class": "content-block-right",
  "id": "",
  "name": "Betende Juden auf einem Schiff nach Palästina",
  "Sammlungsbereich": "Fotografische Sammlung",
  "Gattung": "Fotografie (s/w)\nHerbert Sonnenfeld (29.9.1906 - 1972)",
  "year": "",
  "year1": "1935",
  "metadata": "Fotografie, 1933 – 1937</br>\n3,5 &#215; 4,5 cm</br>\n",
  "text": "Männer beten auf einem Schiff vermutlich auf dem Weg nach Palästina.\nevtl.: an Bord der \"Tel Aviv\" nach Palästina, vgl. \"Israelitisches Familienblatt\", 28.02.1935, 14.03.1935 mit dem Artikel \"Besinnliche Fahrt ins Land der Juden\"",
  "emNumber": "",
  "em": "",
  "subtitle": "Literatur- und Abbildungsnachweis:\nN.N.: Auswanderer, in: Israelitisches Familienblatt (2.9.1937), Berlin: Buchdruckerei und Verlagsanstalt Max Leßmann 1937.",
  "Link": "http://objekte.jmberlin.de/object/jmb-obj-127754",
  "imgName": "144087_image.jpg",
  "imgLink": "http://objekte.jmberlin.de/image/jmb-img-144087"
}, {
  "type": "content",
  "class": "content-block-middle-left",
  "id": "",
  "name": "Als jüdische Zeitungen noch frei verkauft werden durften",
  "Sammlungsbereich": "Fotografische Sammlung",
  "Gattung": "Fotografie (s/w)\nHerbert Sonnenfeld (29.9.1906 - 1972)",
  "year": "",
  "year1": "1935",
  "metadata": "Fotografie</br>\nBerlin, 1935</br>\n3,6 &#215; 2,4 cm</br>\n",
  "text": "Ein Zeitungskiosk mit jüdischen Zeitungen vor einem Kiosk in Berlin.",
  "emNumber": "",
  "em": "",
  "subtitle": "Literatur- und Abbildungsnachweis:\nStiftung Jüdisches Museum Berlin (Hg.): Geschichten einer Ausstellung. Zwei Jahrtausende deutsch-jüdische Geschichte, Kat. Jüdisches Museum Berlin, Berlin: Proprietas-Verlag, 2. Auflage, 2002. Christian Dietrich: Verweigerte Anerkennung - Selbsbestimmungsdebatten im \"Centralverein deutscher Staatsbürger jüdischen Glaubens\" vor dem Ersten Weltkrieg, Metropol Verlag 2014, Cover Krüger, Maren (Hg.): Herbert Sonnenfeld. Ein jüdischer Fotograf in Berlin 1933-1939, Kat. Berlin-Museum / Abteilung Jüdisches Museum, Berlin: Nicolaische Verl.buchh. 1990, S. 12.",
  "Link": "http://objekte.jmberlin.de/object/jmb-obj-102877",
  "imgName": "117905_image.jpg",
  "imgLink": "http://objekte.jmberlin.de/image/jmb-img-117905"
}, {
  "type": "section",
  "class": "timeline-section-left",
  "id": "",
  "name": "",
  "Sammlungsbereich": "",
  "Gattung": "",
  "year": "1936",
  "year1": "",
  "metadata": "",
  "text": "Der »Jüdische Weltkongress« wird in Genf gegründet.",
  "emNumber": "",
  "em": "",
  "subtitle": "",
  "Link": "",
  "imgName": "",
  "imgLink": ""
}, {
  "type": "content",
  "class": "content-block-middle-right",
  "id": "",
  "name": "Junge Chaluzim nehmen durchs Fenster Abschied von ihren Angehörigen",
  "Sammlungsbereich": "Fotografische Sammlung",
  "Gattung": "Fotografie (s/w)\nHerbert Sonnenfeld (29.9.1906 - 1972)",
  "year": "",
  "year1": "",
  "metadata": "Fotografie (s/w-Negativfilm)</br>\nBerlin, 01.&#x2009;09.1936</br>\n2,4 &#215; 3,6 cm</br>\n",
  "text": "Junge Emigranten hängen aus dem Fenster des Zuges von Berlin nach Marseille. Sie verabschieden sich von ihren Angehörigen am Anhalter Bahnhof in Berlin.\nUm der drohenden Einwanderungssperre durch die britische Mandatsregierung zuvorzukommen, stellte das Palästina-Amt mit Hilfe des Palestine & Orient-Lloyd innerhalb von wenigen Tagen für den 02.09.1936 einen Sonderzug Berlin - Marseille zu Verfügung, der 650 Emigranten zum Dampfer Marseille - Palästina brachte (der frz. Dampfer \"Patria\").\nEs war der größte Auswanderertransport, der Deutschland bis dahin verlassen hatte. Etwa die Hälfte der Emigranten bestieg den Zug am Anhalter Bahnhof in Berlin, der Rest stieg in anderen Orten Deutschlands zu.",
  "emNumber": "",
  "em": "",
  "subtitle": "",
  "Link": "http://objekte.jmberlin.de/object/jmb-obj-155627",
  "imgName": "155628_image.jpg",
  "imgLink": "http://objekte.jmberlin.de/image/jmb-img-155628"
}, {
  "type": "content",
  "class": "content-block-left",
  "id": "",
  "name": "Der Sonderzug von Berlin nach&nbsp;Marseille\n",
  "Sammlungsbereich": "Fotografische Sammlung",
  "Gattung": "Fotografie (s/w)\nHerbert Sonnenfeld (29.9.1906 - 1972)",
  "year": "",
  "year1": "1936",
  "metadata": "Fotografie</br>\nBerlin, 01.&#x2009;09.1936</br>\n17,8 &#215; 24 cm</br>\n",
  "text": "Weitere Abbildung von junge Emigranten im Sonderzug nach Marseille. Sie nehmen aus dem Fenster des Zuges Abschied von ihren Angehörigen am Anhalter Bahnhof in Berlin.\nDas Palästina-Amt stellte mit Hilfe des Palestine & Orient-Lloyd innerhalb von wenigen Tagen für den 02.09.1936 einen Sonderzug Berlin - Marseille zu Verfügung, der 650 Emigranten zum Dampfer Marseille - Palästina brachte (der frz. Dampfer \"Patria\").\n",
  "emNumber": "",
  "em": "",
  "subtitle": "Literatur- und Abbildungsnachweis:\nJüdisches Nachrichtenblatt Nr. 48 (16.06.1939), Berlin 1939.",
  "Link": "http://objekte.jmberlin.de/object/jmb-obj-122951",
  "imgName": "169413_image.jpg",
  "imgLink": "http://objekte.jmberlin.de/image/jmb-img-169413"
}, {
  "type": "section",
  "class": "timeline-section-right",
  "id": "black-start",
  "name": "",
  "Sammlungsbereich": "",
  "Gattung": "",
  "year": "1938",
  "year1": "",
  "metadata": "",
  "text": "In der »Kristallnacht« werden im Deutschen Reich Synagogen angezündet, Geschäfte und Wohnungen zerstört und Menschen angegegriffen.\nDie entstandenen Kosten werden den Juden durch eine Sondersteuer auferlegt.",
  "emNumber": "",
  "em": "",
  "subtitle": "",
  "Link": "",
  "imgName": "",
  "imgLink": ""
}, {
  "type": "content",
  "class": "content-block-right",
  "id": "",
  "name": "Briefe schreibende Kinder kurz vor ihrer Auswanderung nach Palästina",
  "Sammlungsbereich": "Fotografische Sammlung",
  "Gattung": "Fotografie (s/w)\nHerbert Sonnenfeld (29.9.1906 - 1972)",
  "year": "",
  "year1": "1938",
  "metadata": "Fotografie, Tusche</br>\nTriest, 1938</br>\n23,5 &#215; 17 cm\n",
  "text": "Drei Kinder, zwei Jungen und ein Mädchen, sitzen am Hafen von Triest, von wo aus sie nach Palästina auswandern werden, an der Schiffsanlegestelle und schreiben Briefe. \nDas Foto ist retuschiert.",
  "emNumber": "",
  "em": "",
  "subtitle": "Beschriftung Rückseite:\n(handschriftl.:) Einschiffung - Triest, 1938 / 1spaltig / Doublette / Feuilleton / (Stempel:) Abdruck oder Reproduktion / nur nach Genehmigung durch: / Herbert Sonnenfeld, Berlin W15 / Joachimsthaler Str. 28 J1 Bismarck 6845 // (handschriftl.:) Auswanderung: Kinder schreiben Briefe / Bildarchive // (Stempel.:) Abraham Pisarek // Leihweise // Bildarchiv / Abraham Pisarek / Gelfertstraße 17, 1000 Berlin 33",
  "Link": "http://objekte.jmberlin.de/object/jmb-obj-177986",
  "imgName": "178050_image.jpg",
  "imgLink": "http://objekte.jmberlin.de/image/jmb-img-178050"
}, {
  "type": "section",
  "class": "timeline-section-left",
  "id": "",
  "name": "",
  "Sammlungsbereich": "",
  "Gattung": "",
  "year": "1939",
  "year1": "",
  "metadata": "",
  "text": "Beginn von Deportationen aus Österreich und Böhmen-Mähren nach Polen.",
  "emNumber": "",
  "em": "",
  "subtitle": "",
  "Link": "",
  "imgName": "",
  "imgLink": ""
}, {
  "type": "content",
  "class": "content-block-middle-left",
  "id": "",
  "name": "Häftlingsjacke aus dem Konzentrationslager Auschwitz",
  "Sammlungsbereich": "Alltagskultur",
  "Gattung": "Textil (weltlicher Gebrauch)",
  "year": "",
  "year1": "1939",
  "metadata": "Wolle, Kunststoffknöpfe; Metallhaken</br>\nAuschwitz, 1939 – 1945</br>\n70 &#215; 90 &#215; 5 cm</br>\nÄrmellänge: 54 cm",
  "text": "Diese Häftlingsjacke gehörte Max Mayer Sprecher (1909-1980), der in Berlin Medizin und jüdische Theologie studiert hatte. Im September 1939 wurde er auf der Straße verhaftet und ins Konzentrationslager Sachsenhausen eingeliefert.\nNach dreijähriger Haft wurde er mit anderen jüdischen Häftlingen nach Auschwitz transportiert. Dort musste er die Zwillinge betreuen, die der KZ-Arzt Josef Mengele für seine Menschenversuche missbrauchte.\nAls die SS vor der heranrückenden Roten Armee flüchtete und Auschwitz im Januar 1945 räumte, gehörte Sprecher zu den Häftlingen, die auf langen Todesmärschen ins Reichsinnere getrieben wurden. Max Mayer Sprecher überlebte und wurde von der US-amerikanischen Armee in Tirol befreit. ",
  "emNumber": "",
  "em": "",
  "subtitle": "Literatur- und Abbildungsnachweis:\nStiftung Jüdisches Museum Berlin (Hg.): Geschichten einer Ausstellung. Zwei Jahrtausende deutsch-jüdische Geschichte, Kat. Jüdisches Museum Berlin, Berlin: Proprietas-Verlag, 2. Auflage, 2002.",
  "Link": "http://objekte.jmberlin.de/object/jmb-obj-106952",
  "imgName": "121911_image.jpg",
  "imgLink": "http://objekte.jmberlin.de/image/jmb-img-121911"
}, {
  "type": "content",
  "class": "content-block-middle-right",
  "id": "",
  "name": "Anhänger vom Kindertransport von Kurt Treitel",
  "Sammlungsbereich": "Archiv",
  "Gattung": "Urkunde",
  "year": "",
  "year1": "1939",
  "metadata": "Kreide, Karton</br>\nBerlin, 1939</br>\n8 &#215; 15,8 cm\n",
  "text": "Anhänger von Kurt Treitel (geb. 1922), der zusammen mit seinem Bruder Günter am 21. März 1939 von Berlin aus mit einem Kindertransport nach England gelangte. Jedes Kind, das mit dem Kindertransport in England ankam, hatte einen derartigen Anhänger um den Hals, auf dem der Name stand (hier mit dem Zwangszusatz \"Israel\", mit dem die deutschen Behörden Kurt Treitel als Juden kennzeichneten), sowie eine dem Kind zugeordnete Nummer von den Organisatoren der Transporte.",
  "emNumber": "",
  "em": "",
  "subtitle": "",
  "Link": "http://objekte.jmberlin.de/object/jmb-obj-312791?cid=253676",
  "imgName": "458139_image.jpg",
  "imgLink": "http://objekte.jmberlin.de/image/jmb-img-458139"
}, {
  "type": "section",
  "class": "timeline-section-left",
  "id": "",
  "name": "",
  "Sammlungsbereich": "",
  "Gattung": "",
  "year": "1941",
  "year1": "",
  "metadata": "",
  "text": "Im Zuge der so genannten »Endlösung der Judenfrage« der Nationalsozialisten werden etwa 6&nbsp;Millionen Juden umgebracht. ",
  "emNumber": "",
  "em": "",
  "subtitle": "",
  "Link": "",
  "imgName": "",
  "imgLink": ""
}, {
  "type": "content",
  "class": "content-block-left",
  "id": "",
  "name": "Rot-Kreuz-Brief von Marianne Simion an ihre Mutter",
  "Sammlungsbereich": "Archiv",
  "Gattung": "Postmitteilung",
  "year": "",
  "year1": "1942",
  "metadata": "Papier, Kopierstift, Tinte, Stempelfarbe</br>\nLondon, um 1942</br>\n22,7 &#215; 14,6 cm\n",
  "text": "Das Internationale Rote Kreuz hatte 1936 begonnen, einen Nachrichtendienst aufzubauen. Während des Zweiten Weltkrieges beteiligten sich daran über 100 nationale Rote-Kreuz-Gesellschaften. Familien konnten sich auf einem Formblatt mit höchstens 25 Wörtern Mitteilungen schreiben. Oft erreichten sie ihre Empfänger erst Monate später. \nDiese Mitteilungen stammen von Marianne Simion (1893-1973) in London, wohin sie ausgewandert war, und ihrer Mutter Emma Warschauer (1861-1944)  in Berlin und Theresienstadt.",
  "emNumber": "",
  "em": "",
  "subtitle": "Literatur- und Abbildungsnachweis:\nHeft \"7x versteckt\", Artikel zum Brief von Jenny Gebel, in: Jüdisches Museum Berlin (Hg.): gesammelt gefaltet gezählt, Nicolai Verlag 2009.",
  "Link": "http://objekte.jmberlin.de/object/jmb-obj-404080",
  "imgName": "367674_image.jpg",
  "imgLink": "http://objekte.jmberlin.de/image/jmb-img-367674"
}, {
  "type": "content",
  "class": "content-block-right",
  "id": "",
  "name": "Namenliste von Frauen im Rigaer Ghetto",
  "Sammlungsbereich": "Archiv",
  "Gattung": "Manuskript, Typoskript",
  "year": "",
  "year1": "1943",
  "metadata": "Riga, 15.&#x2009;07.&#x2009;1943<br>\n29,5 &#215; 20,5 cm\n",
  "text": "\"Nachstehende Frauen aus den liquidierten Einheiten vom 16. Juli müssen morgen früh um 8.00 Uhr Blechplatz antreten: \"\nEs folgt eine Liste von 108 Namen der betroffenen Frauen mit Angabe ihres Herkunftsortes.",
  "emNumber": "",
  "em": "",
  "subtitle": "",
  "Link": "http://objekte.jmberlin.de/object/jmb-obj-116602",
  "imgName": "122440_image.jpg",
  "imgLink": "http://objekte.jmberlin.de/image/jmb-img-122440"
}, {
  "type": "content",
  "class": "content-block-middle-left",
  "id": "",
  "name": "Passfotos jüdischer Zwangsarbeiter der Firma Ehrich & Graetz AG",
  "Sammlungsbereich": "Fotografische Sammlung",
  "Gattung": "Fotografie (s/w)",
  "year": "",
  "year1": "1943",
  "metadata": "Fotografie, Pergamin, Pappe</br>\nBerlin, 1940 – 1943</br>\nGröße je Paßfoto: 5 cm &#215; 3,8 cm</br>\n",
  "text": "Eine Mitarbeiterin der Firma Ehrich & Graetz in Berlin-Treptow bewahrte über 500 Fotos von jüdischen Deutschen auf, die in der Metall-Fabrik Zwangsarbeit leisten mussten. Juden wurden in dem Betrieb eingesetzt, als im Herbst 1940 die generelle Verpflichtung für Juden zur Zwangsarbeit eingeführt wurde. \nIn der so genannten Fabrik-Aktion vom 27. Februar 1943 wurden in Berlin über 12.000 jüdische Zwangsarbeiter direkt an ihren Arbeitsplätzen von der Gestapo verhaftet und deportiert, auch die von Ehrich & Graetz. Berlin sollte \"judenrein\" gemacht werden. Nur einzelnen gelang es, sich der Festnahme zu entziehen und unterzutauchen.\" ",
  "emNumber": "",
  "em": "",
  "subtitle": "Literatur- und Abbildungsnachweis:\nStiftung Jüdisches Museum Berlin (Hg.): Geschichten einer Ausstellung. Zwei Jahrtausende deutsch-jüdische Geschichte, Kat. Jüdisches Museum Berlin, Berlin: Proprietas-Verlag, hallo2. Auflage, 2002. Aufruf im AUFBAU, 23. Juni 1989, S. 3-4: Schachteln - gefüllt mit Schicksalen. Fotos jüdischer Zwangsarbeiter in Berlin gefunden",
  "Link": "http://objekte.jmberlin.de/object/jmb-obj-102520?cid=325440",
  "imgName": "121222_image.jpg",
  "imgLink": "http://objekte.jmberlin.de/image/jmb-img-121222"
}, {
  "type": "content",
  "class": "content-block-middle-right",
  "id": "",
  "name": "Innenansicht einer Baracke",
  "Sammlungsbereich": "Kunst",
  "Gattung": "Handzeichnung, Aquarell\n? Theiner",
  "year": "",
  "year1": "1943",
  "metadata": "Bleistift</br>\nTheresienstadt, 1943</br>\n11,6  &#215; 16 cm",
  "text": "Blick in eine Baracke mit Doppelstockbetten, an den Rand jeden Bettes sind die Namen der Besitzer geschrieben; im Vordergrund ein Tisch mit verschiedenen Utensilien, darunter eine Brotlaib, ein Löffel und ein Topf; am Tisch sitzt ein bärtiger Mann.",
  "emNumber": "",
  "em": "",
  "subtitle": "",
  "Link": "http://objekte.jmberlin.de/object/jmb-obj-146447?cid=324833",
  "imgName": "146472_image.jpg",
  "imgLink": "http://objekte.jmberlin.de/image/jmb-img-146472"
}, {
  "type": "content",
  "class": "content-block-left",
  "id": "",
  "name": "Letztes Lebenszeichen vor der&nbsp;Deportation",
  "Sammlungsbereich": "Archiv",
  "Gattung": "Manuskript, Typoskript",
  "year": "",
  "year1": "1943",
  "metadata": "Bleistift, Papier</br>\nBerlin, 1943</br>\n25,5 &#215; 15,5 cm",
  "text": "Handschriften von Kurt, Margarete und Peter Rosenbaum. Neben der Handschrift des Sohnes Peter sind 44 Kringel gemalt, am oberen Rand weitere 70 Kringel mit dem Zusatz \"70 Küsse\".",
  "emNumber": "",
  "em": "",
  "subtitle": "",
  "Link": "http://objekte.jmberlin.de/object/jmb-obj-117354?cid=325734",
  "imgName": "122681_image.jpg",
  "imgLink": "http://objekte.jmberlin.de/image/jmb-img-122681"
}, {
  "type": "content",
  "class": "content-block-right",
  "id": "",
  "name": "Ausweis für Cilly Meyer im Ghetto Schanghai",
  "Sammlungsbereich": "Archiv",
  "Gattung": "Urkunde",
  "year": "",
  "year1": "1944",
  "metadata": "Papier oder Karton, Tinte, Stempelfarbe</br>\nSchanghai, 21.&#x2009;04.1944</br>\n9,2 &#215; 14,6 cm\n",
  "text": "Am 12.05.1943 musste Cilly Meyer (1898-1978) gemeinsam mit ihrer Familie in den von den Japanern eingerichteten Ghetto-Bezirk Hongkew in Schanghai umziehen. Der Ausweis enthält Angaben zur Person, ein Passfoto, 2 Fingerabdrücke und einen gelben Streifen, der die Inhaberin als Jüdin ausweist.",
  "emNumber": "",
  "em": "",
  "subtitle": "",
  "Link": "http://objekte.jmberlin.de/object/jmb-obj-486530",
  "imgName": "486562_image.jpg",
  "imgLink": "http://objekte.jmberlin.de/image/jmb-img-486562"
}, {
  "type": "content",
  "class": "content-block-middle-left",
  "id": "",
  "name": "\"Transportnummer\" von Rosa Stein im Konzentrationslager Theresienstadt",
  "Sammlungsbereich": "Alltagskultur",
  "Gattung": "Textil (weltlicher Gebrauch)",
  "year": "",
  "year1": "1944",
  "metadata": "Baumwolle, Faserstift</br>\nTheresienstadt, 04.&#x2009;09.1944</br>\n4,3 &#215; 7,1 cm</br>\n",
  "text": "Rosa (1901-1977) und Fritz (1891-1945) Stein wanderten 1939 aus Deutschland in die Niederlande aus. Nach der deutschen Besetzung wurde das Paar 1944 in das Lager Westerbork und von dort nach Theresienstadt deportiert. Rosa Stein überlebte und zog nach Frankreich. Ihren Mann deportierten die Nationalsozialisten von Theresienstadt nach Auschwitz und Dachau. Dort starb er im März 1945, kurz vor der Befreiung des Lagers durch amerikanische Truppen.",
  "emNumber": "",
  "em": "",
  "subtitle": "",
  "Link": "http://objekte.jmberlin.de/object/jmb-obj-425080",
  "imgName": "425679_image.jpg",
  "imgLink": "http://objekte.jmberlin.de/image/jmb-img-425679"
}, {
  "type": "section",
  "class": "timeline-section-right",
  "id": "",
  "name": "",
  "Sammlungsbereich": "",
  "Gattung": "",
  "year": "1945",
  "year1": "",
  "metadata": "",
  "text": "Anne Frank stirbt im Konzentrationslager Bergen&#8209;Belsen.",
  "emNumber": "",
  "em": "",
  "subtitle": "",
  "Link": "",
  "imgName": "",
  "imgLink": ""
}, {
  "type": "content",
  "class": "content-block-middle-right",
  "id": "",
  "name": "Stoffbahn mit aufgedruckten \"Judensternen\"",
  "Sammlungsbereich": "Alltagskultur",
  "Gattung": "Textil (weltlicher Gebrauch)",
  "year": "",
  "year1": "1945",
  "metadata": "Viskose, bedruckt</br>\nDeutschland, 1941 – 1945</br>\n75 &#215; 121 cm</br>",
  "text": "Stoffbahn mit aufgedruckten \"Judensternen\"; \nauf gelbgefärbter Viskose sind insgesamt 77 sogenannte Judensterne, ein Davidstern mit der Inschrift \"Jude\", zum Ausschneiden aufgedruckt. \nAb September 1941 war das sichtbare Tragen des Sterns für die im Deutschen Reich lebenden Juden verpflichtend. ",
  "emNumber": "",
  "em": "",
  "subtitle": "Literatur- und Abbildungsnachweis:\nZum historischen Kontext s. \"Bitter Bonnets and Badges\", in: Eric Silverman: A Cultural History of Jewish Dress , London, New York, 2013, S. 47-67 ZEIT Geschichte. Epochen. Menschen. Ideen. Heft Nr. 1, Jg. 2017: Der Weg in den Holocaust. Die Wannsee-Konferenz und die \"Endlösung der Judenfrage\", S. 3",
  "Link": "http://objekte.jmberlin.de/object/jmb-obj-103336",
  "imgName": "121402_image.jpg",
  "imgLink": "http://objekte.jmberlin.de/image/jmb-img-121402"
}, {
  "type": "content",
  "class": "content-block-left",
  "id": "",
  "name": "Lebensmittelkarte für Paul&nbsp;N.&nbsp;Pulvermann",
  "Sammlungsbereich": "Archiv",
  "Gattung": "Druckerzeugnis",
  "year": "",
  "year1": "1945",
  "metadata": "Papier, Tinte, Stempelfarbe</br>\nBerlin, 01.&#x2009;04.1945</br>\n16,5 &#215; 15,8 cm",
  "text": "Ergänzungskarte zur Grundkarte vom Ernährungsamt Berlin für Paul N. Pulvermann ausgestellt auf seinen zwangsweise angenommenen Vornamen Uri (1896-1984), mit dem Aufdruck \"Jude\" versehen. Die Karten sind vorgesehen für Nährmittel, Stärkeerzeugnisse, Brot und Fleisch. Einige Karten wurden abgerissen, die meisten verbliebenen mit einem \"ungültig\"-Stempel versehen.",
  "emNumber": "",
  "em": "",
  "subtitle": "Literatur- und Abbildungsnachweis:\nAlice Weinreb, Modern Hungers - Food and Power in Twentieth-Century Germany, Oxford University Press, 2017, S. 77",
  "Link": "http://objekte.jmberlin.de/object/jmb-obj-127417",
  "imgName": "128172_image.jpg",
  "imgLink": "http://objekte.jmberlin.de/image/jmb-img-474170"
}, {
  "type": "content",
  "class": "content-block-right",
  "id": "black-end",
  "name": "Hochzeitseinladung aus&#8209;dem DP Lager Bergen&#8209;Belsen",
  "Sammlungsbereich": "Archiv",
  "Gattung": "Druckerzeugnis",
  "year": "",
  "year1": "1948",
  "metadata": "Papier</br>\nBergen-Belsen, 06.&#x2009;04.1948</br>\n21 &#215; 14,7 cm</br>\n",
  "text": "Von Braut und Bräutigam sind die Namen der verstorbenen Väter angegeben, die beide Rabbiner waren.\nDer Einladung ist der jüdische Segenspruch: \"Kol Sason veKol Simchah, Kol Chathan veKol Khalah\" <i>die Stimme des Glücks und die Stimme der Freude, die Stimme des Bräutigams und die Stimme der Braut</i> vorangestellt.\nFür Telegramme wird eine Anschrift angegeben: Rechtman, Bergen-Belsen, Camp 5, Block 43 und 10.",
  "emNumber": "",
  "em": "",
  "subtitle": "",
  "Link": "http://objekte.jmberlin.de/object/jmb-obj-459102",
  "imgName": "459157_image.jpg",
  "imgLink": "http://objekte.jmberlin.de/image/jmb-img-459157"
}, {
  "type": "content",
  "class": "content-block-middle-left",
  "id": "",
  "name": "Wahlaufruf der Jüdischen Gemeinde am 30.01.1948",
  "Sammlungsbereich": "Archiv",
  "Gattung": "Druckerzeugnis",
  "year": "",
  "year1": "1948",
  "metadata": "Papier</br>\nBerlin, 09.&#x2009;01.1948</br>\n29,5 &#215; 20,7 cm</br>\n",
  "text": "Auf der Vorderseite stellt die Jüdisch-liberale Gruppe ihr Programm vor. Auf der Rückseite sind der Wahlaufruf und die Liste der Kandidaten verzeichnet.",
  "emNumber": "",
  "em": "",
  "subtitle": "",
  "Link": "http://objekte.jmberlin.de/object/jmb-obj-125775?cid=324414",
  "imgName": "127607_image.jpg",
  "imgLink": "http://objekte.jmberlin.de/image/jmb-img-127607"
}, {
  "type": "section",
  "class": "timeline-section-right",
  "id": "",
  "name": "",
  "Sammlungsbereich": "",
  "Gattung": "",
  "year": "1950",
  "year1": "",
  "metadata": "",
  "text": "Gründung des »Zentralrats der Juden in Deutschland«.",
  "emNumber": "",
  "em": "",
  "subtitle": "",
  "Link": "",
  "imgName": "",
  "imgLink": ""
}, {
  "type": "section",
  "class": "timeline-section-left",
  "id": "",
  "name": "",
  "Sammlungsbereich": "",
  "Gattung": "",
  "year": "1965",
  "year1": "",
  "metadata": "",
  "text": "Aufnahme der diplomatischen Beziehungen zwischen der BRD und Israel.",
  "emNumber": "",
  "em": "",
  "subtitle": "",
  "Link": "",
  "imgName": "",
  "imgLink": ""
}, {
  "type": "section",
  "class": "timeline-section-right",
  "id": "",
  "name": "",
  "Sammlungsbereich": "",
  "Gattung": "",
  "year": "1979",
  "year1": "",
  "metadata": "",
  "text": "Friedensvertrag zwischen Israel und Ägypten.",
  "emNumber": "",
  "em": "",
  "subtitle": "",
  "Link": "",
  "imgName": "",
  "imgLink": ""
}, {
  "type": "content",
  "class": "content-block-middle-right",
  "id": "",
  "name": "Personenbeschreibung eines Familienfotos",
  "Sammlungsbereich": "Archiv",
  "Gattung": "Manuskript, Typoskript",
  "year": "",
  "year1": "1999",
  "metadata": "Netania/Israel, 1999</br>\n22,5 &#215; 32,8 cm\n",
  "text": "Zu sehen sind die Umrisse der Personen, die auf dem Familienfoto von 1928 anläßlich der Bar Mizwa von Siegbert Kindermann versammelt waren. Rita Rubinstein, geb. 1922, ergänzte die Umrisse mit Angaben zum Schicksal der einzelnen Personen. Sie ist die Schwester von Siegbert und unten als die zweite von links auf dem Bild zu sehen. <sup>08</sup>",
  "emNumber": "(08)",
  "em": "Während des Holocaust ließen die meisten Menschen ihre jüdischen Nachbarn im Stich, schauten weg oder beteiligten sich sogar an der Verfolgung der Juden. ",
  "subtitle": "",
  "Link": "http://objekte.jmberlin.de/object/jmb-obj-167299?cid=327029",
  "imgName": "169875_image.jpg",
  "imgLink": "http://objekte.jmberlin.de/image/jmb-img-169875"
}, {
  "type": "content",
  "class": "content-block-left",
  "id": "oneline",
  "name": "Kippa",
  "Sammlungsbereich": "Judaica/Angewandte Kunst",
  "Gattung": "Textil (religiöser Gebrauch)",
  "year": "",
  "year1": "2003",
  "metadata": "Leder, Kunststoff</br>\n2003</br>\n4,5 &#215; &#8709; 13,7 cm</br>\n",
  "text": "Die dunkelblaue Kippa besteht aus Wildleder und ist auf der Oberseite durch zwei lange, dunkelblaue Nähte in vier Felder aufgeteilt. Auf eines der Felder ist eine wehende amerikanische Flagge an einem Fahnenmast aufgemalt. In den drei weiteren Feldern stehen die Namen der US-amerikanischen, demokratischen Präsidentschafts- bzw. Vizepräsidentschaftskandidaten zur Präsidentschaftswahl im Jahr 2000 \"[Al] Gore\" und \"[Joe] Liebermann\".\nDiese Kippa demonstriert, dass das Tragen der Kippa neben religiöser auch politische Zugehörigkeit ausdrücken kann. <sup>09</sup>",
  "emNumber": "(09)",
  "em": "Das Tragen der Kippa kann neben religösen auch politische Zugehörigkeit ausdrücken",
  "subtitle": "",
  "Link": "http://objekte.jmberlin.de/object/jmb-obj-176442",
  "imgName": "177778_image.jpg",
  "imgLink": "http://objekte.jmberlin.de/image/jmb-img-177778"
}]

var dataInfo = [{
  "section": "iWrapper1",
  "type": "text-left",
  "class": "info-text-left1",
  "id": "",
  "text": "<h3>WER WIR SIND</h3>\nDas Jüdische Museum Berlin gehört seit seiner Eröffnung 2001 zu den herausragenden Institutionen in der europäischen Museumslandschaft. Wir sind ein lebendiger Ort der Reflexion über die jüdische Geschichte und Kultur sowie über Migration und Diversität in Deutschland. <br/>Unsere Ausstellungen, die Publikationen, die pädagogische Arbeit und unser vielfältiges Veranstaltungsprogramm wenden sich an ein breites Publikum aus Deutschland und der ganzen Welt. Dabei orientieren wir uns an den Interessen unserer BesucherInnen, die von einer eigenen Abteilung durch regelmäßige Befragungen ermittelt werden. In allen Publikumsbereichen finden Sie zudem freundliche und kompetente AnsprechpartnerInnen. Unsere Sammlungen wachsen beständig, auch dank vieler StifterInnen aus dem In- und Ausland.<br/><br>Unser Museum befindet sich in Kreuzberg, nicht weit vom Checkpoint Charlie und der früheren Berliner Mauer. Berühmt ist es für den Museumsbau von Daniel Libeskind, der längst zu einem Wahrzeichen Berlins geworden ist. Der Libeskind-Bau wird ergänzt durch einen Altbau aus der Barockzeit und die W. Michael Blumenthal Akademie, die zusammen das Ensemble Jüdisches Museum Berlin bilden.<br><br/>Ein besonderer Schwerpunkt unserer Museumstätigkeit liegt auf der Bildungsarbeit: Das umfangreiche pädagogische Angebot, die Forschungsmöglichkeiten in Bibliothek und Archiv sowie das vielfältige Veranstaltungsprogramm richten sich an Kinder, Jugendliche und Erwachsene. Neben Führungen und Workshops finden Vorträge, Konzerte und Lesungen statt. Jährlich veranstalten wir einen Kultursommer. <br/><br> Mit den Akademieprogrammen zu Migration und Diversität und dem Jüdisch-Islamischen Forum haben wir Diskussionsplattformen geschaffen. Thema sind die politischen, sozialen und kulturellen Bedingungen, unter denen Minderheiten hierzulande leben und an der Gesellschaft teilhaben können."
}, {
  "section": "iWrapper1",
  "type": "text-right",
  "class": "info-text-right1",
  "id": "",
  "text": "<h3>DER LIBESKIND-BAU</h3>\n<h4>Architektur erzählt deutsch-jüdische Geschichte</h4><br/>Ein Zick-Zack-Bau aus Titanzink, unterirdische Achsen, schiefe Wände und unklimatisierte Betonschächte: Mit seinem Entwurf Between the Lines wollte der US-amerikanische Architekt Daniel Libeskind nicht einfach ein Museumsgebäude gestalten, sondern deutsch-jüdische Geschichte erzählen. Noch vor der Eröffnung des Jüdischen Museums Berlin im Herbst 2001 besichtigten knapp 350.000 Menschen den leeren Museumsbau, der immer noch zahlreiche Gäste aus dem In- und Ausland fasziniert. Heute befindet sich im Libeskind-Bau unsere Dauerausstellung, die derzeit jedoch umgebaut wird und daher nicht zugänglich ist. Das Gebäude lässt viele Interpretationen zu: Manche erinnert es an einen zerbrochenen Davidstern, andere an einen Blitz; bei vielen hinterlässt es ein Gefühl der Verunsicherung oder Desorientierung.\n<br><br><br><br><h4>Between the Lines: Daniel Libeskind und sein Entwurf</h4><br/>Mit seinem Entwurf Between the Lines (Zwischen den Linien) hatte der Architekt Daniel Libeskind 1989 den Wettbewerb für den »Erweiterungsbau des Berlin Museums mit Abteilung Jüdisches Museum« gewonnen. Es war sein erster Entwurf, der tatsächlich baulich umgesetzt wurde.<br/><br>Äußerlich ist der Libeskind-Bau eigenständig, vom Eingangsbereich im benachbarten barocken Altbau gelangen BesucherInnen nur durch eine unterirdische Verbindung in die Dauerausstellung. Den Grundriss entwickelte Daniel Libeskind aus zwei Linien: der sichtbaren Zick-Zack-Linie des Gebäudes und einer unsichtbaren geraden Linie. An den Kreuzungspunkten liegen die Voids, Leerräume, die das Gebäude vom Untergeschoss bis zum Dach durchziehen. Die sich kreuzenden und schräg verlaufenden Fenster wirken unsystematisch und lassen von außen keine Geschossgliederung erkennen.\n"
}, {
  "section": "iWrapper1",
  "type": "quote",
  "class": "info-text-quote1",
  "id": "quote1",
  "text": "»Der offizielle Name des Projekts lautet ›Jüdisches Museum‹, aber ich habe es ›Between the Lines‹ genannt, weil es sich für mich dabei um zwei Linien, zwei Strömungen des Denkens, der Organisation und Beziehungen handelt.« </br> \n<span class=\"author\">- DANIEL LIBESKIND -</span>"
}, {
  "section": "iWrapper1",
  "type": "text-left",
  "class": "info-text-left2",
  "id": "",
  "text": "<h3>Geschichte des Jüdischen Museum Berlin</h3>\nDas Jüdische Museum Berlin öffnete im Jahr 2001. Noch in der Zeit vor dem Mauerfall 1989 kamen im Westteil Berlins Überlegungen auf, ein Jüdisches Museum zu gründen. Der Weg von dieser Idee bis zur Konzeption seiner Dauerausstellung war lang und von Kontroversen geprägt.<br/><br>Mit der Ernennung W. Michael Blumenthals zum Direktor wurde das Museum schließlich nicht – wie ursprünglich geplant – bloß als Abteilung des landeseigenen Berlin Museums konzipiert. Der 1926 in Berlin geborene und als 13-Jähriger nach Shanghai und später in die USA emigrierte Blumenthal setzte vielmehr die Eigenständigkeit des Hauses durch. 2001 wurde das Jüdische Museum Berlin dann vom Bund übernommen und zu einer bundesunmittelbaren Stiftung. <br><br><br><br><h4>Konzeption der Ausstellung und Museumseröffnung</h4> <br/>Damit einhergehend wurde das Jüdische Museum Berlin auch zum alleinigen Nutzer des Gebäudeensembles in der Lindenstraße: dem barocken Altbau, der zuvor das Berlin Museum beherbergt hatte, und dem Erweiterungsbau von Daniel Libeskind.\n\n\n\n"
}, {
  "section": "iWrapper1",
  "type": "text-right",
  "class": "info-text-right2",
  "id": "",
  "text": "Libeskind selbst nennt für seinen Entwurf vier Inspirationsquellen: Für die Verbindung zwischen jüdischer Tradition und deutscher Kultur vor der Schoa stehen jüdische und nicht-jüdische Berliner Persönlichkeiten wie Paul Celan, Max Liebermann, Heinrich von Kleist, Rahel Varnhagen oder Friedrich Hegel. Aus deren Adressen entstand ein Liniennetz, aus dem Libeskind die Struktur des Gebäudes und der Fenster entwickelte. Weitere Anregungen erhielt der Architekt aus der unvollendeten Oper Moses und Aron des Komponisten Arnold Schönberg, aus dem Gedenkbuch des Bundesarchivs für die Opfer der nationalsozialistischen Judenverfolgung in Deutschland (1933–1945) sowie aus Walter Benjamins Essay Einbahnstraße.<br><br><br><br><h4>Die Voids</h4><br>\n\nDie Voids durchziehen vertikal das Gebäude. Die Betonschächte sind unklimatisiert, weitgehend ohne künstliche Beleuchtung und können nur zum Teil betreten werden. In den oberen Ausstellungsgeschossen sind sie deutlich erkennbar durch die Void-Brücken markiert, deren Wände schwarz gestrichen sind. Einer der fünf Leerräume beherbergt die Installation Schalechet (Gefallenes Laub) des israelischen Künstlers Menashe Kadishman (weitere Informationen zur Installation Schalechet auf unserer Website)."
}, {
  "section": "iWrapper1",
  "type": "text-left",
  "class": "info-text-left3",
  "id": " ",
  "text": "Der neuseeländische Anthropologe und Museumsmanager Kenneth C. Gorbey und sein Mitarbeiter Nigel Cox, beide involviert in die Konzeption und Ausführung des neuseeländischen Nationalmuseums Te Papa, koordinierten und realisierten die Dauerausstellung.<br><br>\nAm 9. September 2001 eröffnete das Jüdische Museum Berlin mit einem festlichen Konzert unter der Leitung von Daniel Barenboim. Beim anschließenden Gala-Dinner sprachen der damalige Bundespräsident Johannes Rau und W. Michael Blumenthal vor 850 prominenten Gästen aus Politik, Wirtschaft und Kultur aus dem In- und Ausland.<br><br>\n\nDie Öffnung für das Publikum war für den 11. September 2001 geplant und musste wegen der Terroranschläge auf das World Trade Center in New York um zwei Tage verschoben werden. Zeitgleich mit dem Museum eröffnete auch das multimediale Rafael Roth Learning Center im Untergeschoss des Libeskind-Baus. Bis März 2017 lud es BesucherInnen ein, an 20 Computerstationen durch vielfältige Medienanwendungen mit Dokumenten, Objekten, Filmen, Tonaufnahmen und interaktiven Spielen jüdische Geschichte und Kultur zu entdecken.<br><br>\n\nSeit der Eröffnung besichtigten jährlich etwa 700.000, d. h. täglich etwa 2.000 Menschen das Jüdische Museum Berlin. Am 19. November 2015 konnten wir unsere zehnmillionste Besucherin begrüßen. Nach gut 15 Jahren arbeiten wir derzeit am Konzept einer neuen Dauerausstellung.<br><br><br>\n\n\n<br><h4>Neuerungen für Bildung und Forschung</h4><br>\n\nSchon seit Beginn liegt ein besonderer Schwerpunkt unserer Museumstätigkeit auf der Bildungsarbeit. Im Jahr 2007 wurde zudem die Bildungsinitiative »on.tour – Das Jüdische Museum Berlin macht Schule« ins Leben gerufen, bei der das Museum mit einem Tourbus und einer mobilen Ausstellung Schulen in allen Bundesländern besucht. Außerdem erstellen wir Unterrichtsmaterialien für Schulen.<br><br>\n\nIm November 2012 ging eine Datenbank mit ausgewählten Beständen unserer Sammlung online: http://objekte.jmberlin.de. Ebenfalls im November 2012 wurde ein neues, von Daniel Libeskind umgestaltetes Gebäude eröffnet: die Akademie des Jüdischen Museums Berlin. Im Zuge dessen wurden 2013 auch unsere Akademieprogramme ins Leben gerufen, die aus einem Themenschwerpunkt zu Migration und Diversität sowie einem Jüdisch-Islamischen Forum bestehen."
}, {
  "section": "iWrapper1",
  "type": "text-right",
  "class": "info-text-right3",
  "id": " ",
  "text": "<h4>Die Achsen im Untergeschoss</h4>\n\nIm Untergeschoss des Libeskind-Baus kreuzen sich drei Achsen, die symbolisch für die unterschiedliche Entwicklung jüdischer Lebensgeschichten in Deutschland stehen: die Achse des Exils, die Achse des Holocaust und die Achse der Kontinuität, die in einer steilen Treppe mündet. Über 82 Stufen gelangen die BesucherInnen zum Eingang der Dauerausstellung im 2. Obergeschoss, weitere acht Stufen enden vor einer weißen Wand.<br><br>\n\nEntlang der Achsen zeigen wir Objekte, die Geschichten von JüdInnen erzählen, die während der Zeit des Nationalsozialismus verfolgt und ermordet wurden oder emigrieren mussten. Am Kreuzungspunkt der drei Achsen befand sich bis Ende März 2017 das Rafael Roth Learning Center.<br><br><br><br> \n\n<h4>Der Holocaust-Turm</h4>\n\nDie Achse des Holocaust endet im Voided Void (entleerte Leere), auch Holocaust-Turm genannt, einem isolierten Gebäudesplitter, der nur unterirdisch mit dem Libeskind-Bau verbunden ist. Tageslicht dringt ausschließlich durch einen schmalen Schlitz in den unbeheizten Betonschacht, Außengeräusche sind nur gedämpft zu hören. Bei vielen BesucherInnen löst der sogenannte Holocaust-Turm ein Gefühl der Beklemmung aus.<br><br><br><br>\n\n\n<h4>Der Garten des Exils</h4>\n\nDie Achse des Exils führt in den Garten des Exils, der außerhalb des Libeskind-Baus liegt. 49 quadratisch angeordnete Stelen stehen auf einer schiefen Ebene. Daraus wachsen Ölweiden als Symbol der Hoffnung. 48 Stelen sind mit Erde aus Berlin gefüllt, die 49. Stele in der Mitte enthält Erde aus Jerusalem.<br><br>\n\nDer Garten des Exils erzeugt bei den BesucherInnen aufgrund der Schräglage ein Gefühl des Schwindels und der Desorientierung, die einzige Vegetation befindet sich in unerreichbarer Höhe. Mit dieser räumlichen Erfahrung wollte Daniel Libeskind auf die mangelnde Orientierung und Haltlosigkeit verweisen, die EmigrantInnen empfanden, die aus Deutschland vertrieben wurden."
}, {
  "section": "iWrapper2",
  "type": "text-left",
  "class": "info-text-left1",
  "id": "",
  "text": "<h3>Unsere Ausstellungen</h3>\n\n<h4>Welcome to Jerusalem</h4><br>\nSynagogen, Kirchen und Moscheen prägen unser Bild von Jerusalem. Für JüdInnen Juden, ChristInnen und MuslimInnen aus aller Welt ist die »heilige Stadt« ein wichtiges Zentrum ihres Glaubens. Gleichzeitig ist Jerusalem von außerordentlicher politischer Brisanz, da sowohl Israelis als auch PalästinenserInnen sie als ihre Hauptstadt beanspruchen.<br><br>\n\nVon der Zeit des zweiten Tempels und seiner Eroberung durch Rom über die osmanische Herrschaft und die britische Mandatszeit bis zum 21. Jahrhundert - die Ausstellung Welcome to Jerusalem thematisiert eine Stadtgeschichte, in der Alltag, Religion und Politik unauflöslich miteinander verflochten sind. Zu sehen sind wertvolle historische Objekte und Modelle, die erstmals in Berlin gezeigt werden; ebenso mediale Installationen, die eigens für die Schau entwickelt wurden.<br>\n<br>Arbeiten von Yael Bartana, Mona Hatoum, Gustav Metzger, Fazal Sheikh und weiteren internationalen KünstlerInnen kommentieren historische Ereignisse und politische Positionen. Eine Filmspur mit Interviews aus der Echtzeit-Dokumentation 24h Jerusalem macht die BesucherInnen mit einer in jeder Hinsicht bemerkenswerten und aufregenden Stadt bekannt. – Welcome to Jerusalem!<br><br><br><br>\n\n<h4>res·o·nant</h4><br>\n\nDas Jüdische Museum Berlin präsentiert mit res·o·nant eine begehbare Licht- und Klanginstallation des Düsseldorfer Konzeptkünstlers Mischa Kuball. Die Installation wurde eigens für die neue Ausstellungsfläche im Untergeschoss des Libeskind-Baus geschaffen.<br><br>Auf insgesamt mehr als 350 Quadratmetern bespielt res·o·nant zwei der fünf den Museumsbau vertikal durchziehenden Voids. Diese symbolischen Leerstellen, auf deren Materialität, Wirkung und Bedeutung sich Mischa Kuball bezieht, bilden den Ausgangspunkt für sein Werk. Damit sind diese beiden charakteristischen Voids des Gebäudes seit Eröffnung des Museums 2001 neu zu erleben.<br>\nIn den 24 Meter hohen Räumen werfen rotierende Projektoren Lichtfelder in Form der Void-Grundrisse an Wände und Decken. Mittels drehender Spiegelelemente und Stroboskop-Blitze entsteht eine »Resonanz zwischen Architektur und Haut«, so der Künstler.<br>\nAls wichtiges Element der Installation sind über mehrere im Raum verteilte Lautsprecher jeweils 60-sekündige Soundclips – sogenannte Skits – zu hören, die von mehr als 50 MusikerInnen eigens für res·o·nant produziert wurden.<br><br>Außerhalb des Museums sind bis zum Sommer 2019 verschiedene Interventionen an belebten Plätzen in Berlin geplant. Neben Performances und Konzerten werden auch hier die Grundrisse der Voids im öffentlichen Raum projiziert und damit die physischen Grenzen des Museums überwunden."
}, {
  "section": "iWrapper2",
  "type": "text-right",
  "class": "info-text-right1",
  "id": "",
  "text": "<h3>Unsere Sammlungen</h3>\n<h4>Blick in das Modell eines Wohnzimmers</h4></br></br>\n»Geschichten erzählen mit Objekten« ist ein Leitgedanke unserer Sammeltätigkeit auf allen Gebieten. Dies kann durch herausragende Einzelstücke geschehen ebenso wie durch Ensembles aus unterschiedlichen Objekten, Bildern, Kunstwerken und Dokumenten. So zeigen wir das Leben der deutschen Jüd*innen und der Jüd*innen in Deutschland.</br></br></br></br>\n\n<h4>Sammlungsobjekte</h4></br>\n\nZurzeit umfassen unsere Sammlungen etwa 9.500 Kunstwerke, 1.000 Objekte der Angewandten Kunst, 1.500 des religiösen Gebrauchs sowie 4.500 Objekte der Alltagskultur, 24.000 Fotografien und über 1.700 Konvolute des Archivs sowie die historischen Bestände der Bibliothek mit circa 11.000 Bänden.</br>\n\nDie Sammlungsobjekte dienen dazu, jüdische Kultur und Geschichte auf anschauliche Weise zu vermitteln, Material für die Forschung zur Verfügung zu stellen und nicht zuletzt das Andenken an die Menschen zu bewahren, deren Geschichten sie erzählen.</br></br></br></br>\n\n<h4>Familiensammlungen</h4></br>\n\nEin Herzstück unserer Sammlung sind die Nachlässe von Familien. Sie enthalten alle Arten von Bildern, Gegenständen und Schriftstücken. Zusammen zeigen sie ein lebendiges Bild vom privaten, beruflichen und religiösen Leben. Die Familiensammlungen wurden durch Verfolgung und Emigration hinweg bewahrt und dem Museum von Nachkommen aus aller Welt geschenkt.</br></br></br></br>\n\n<h4>Historische Schwerpunkte</h4></br>\n\nDie meisten Objekte unserer Sammlungen stammen aus dem 19. und der ersten Hälfte des 20. Jahrhunderts. Sie dokumentieren die bürgerliche Lebenswelt und die Moderne sowie Verfolgungs- und Emigrationserfahrungen. Berlin ist dabei ein Schwerpunkt, doch suchen wir als Jüdisches Museum der Bundesrepublik auch Objekte aus anderen Regionen, aus anderen Epochen und zu anderen Themen.</br>\n\nUnser besonderes Interesse beim Ausbau der Sammlung in den nächsten Jahren gilt der Zeit nach 1945 bis in die Gegenwart. Wir würden uns freuen, wenn Sie uns dabei unterstützen, die Sammlung durch interessante Objekte zu erweitern. Machen Sie uns ein Angebot oder spenden Sie an den Förderverein.</br></br>"
}, {
  "section": "iWrapper1",
  "type": "quote",
  "class": "info-text-quote2",
  "id": "quote2-left",
  "text": "»Mit den Voids thematisiert</br> \nphysische Leere, die durch</br> \nund Vernichtung jüdischen</br> enstanden ist und die nicht</br>\nwerden\n "
}, {
  "section": "iWrapper1",
  "type": "quote",
  "class": "info-text-quote2",
  "id": "quote2-right",
  "text": "Daniel Libeskind die</br> \ndie Vertreibung, Zerstörung</br>  \nLebens in der Schoa</br>nachträglich wieder gefüllt</br> \nkann«"
}]
